appVersion: 1.0.0
description: kingbase port 54321 ; local root /data
name: kingbase
version: 1.0.0
keywords:
- database
- kingbase
home: http://www.kingbase.com.cn/
icon: http://www.kingbase.com.cn/Uploads/logo/201808261535284225.png
