apiVersion: v1
kind: Service
metadata:
  name: {{ template "kingbase.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 54321
      targetPort: 54321
{{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
{{- end }}
  selector:
    app: {{ template "kingbase.name" . }}
    release: "{{ .Release.Name }}"

