#Default values for v1.0.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: 192.168.36.252/lxapp/kingbase
  tag: v1.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 54321

